server:
  port: 5000
  
spring:
  application:
    name: smart-home-voice-assistant
  
logging:
  level:
    com.smarthome: INFO
    org.springframework: INFO
    
# 音频处理配置
voice:
  audio:
    silence-threshold: 0.01
    silence-duration: 1.0
    min-speech-duration: 0.5
  stt:
    engine-type: simulated
  nlu:
    engine-type: rule_based 